// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: '// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vign// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curve// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: '// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24,
      grainSize: 2,
      grainColorVariance: 14,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 16// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24,
      grainSize: 2,
      grainColorVariance: 14,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 16,
      curveShadows: 8,
      curveHighlights: -6,
    },
  },
  {
    id: 'hp5',
    name: 'Ilford HP5 Plus',
    descKey// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24,
      grainSize: 2,
      grainColorVariance: 14,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 16,
      curveShadows: 8,
      curveHighlights: -6,
    },
  },
  {
    id: 'hp5',
    name: 'Ilford HP5 Plus',
    descKey: 'desc_hp5',
    swatch: '#3a3a3a',
    state: {
      saturation: -100,
      contrast: 14,
      highlights: -6,
      shadows:// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24,
      grainSize: 2,
      grainColorVariance: 14,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 16,
      curveShadows: 8,
      curveHighlights: -6,
    },
  },
  {
    id: 'hp5',
    name: 'Ilford HP5 Plus',
    descKey: 'desc_hp5',
    swatch: '#3a3a3a',
    state: {
      saturation: -100,
      contrast: 14,
      highlights: -6,
      shadows: 8,
      grainIntensity: 45,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 24,
      vignetteRadius: 58// Film preset definitions. Each preset is a partial effect state applied on top of defaults.
// Values use the same scale as the adjustments sliders (mostly -100..100 or 0..100).
export const filmPresets = [
  {
    id: 'portra',
    name: 'Kodak Portra 400',
    descKey: 'desc_portra',
    swatch: '#d9a878',
    state: {
      exposure: 4,
      temperature: 8,
      tint: -3,
      saturation: -6,
      contrast: -4,
      highlights: -12,
      shadows: 8,
      grainIntensity: 18,
      grainSize: 2,
      grainColorVariance: 12,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 10,
      curveShadows: 6,
      curveHighlights: -4,
    },
  },
  {
    id: 'gold',
    name: 'Kodak Gold 200',
    descKey: 'desc_gold',
    swatch: '#e0a342',
    state: {
      exposure: 3,
      temperature: 14,
      tint: 2,
      saturation: 10,
      contrast: 6,
      highlights: -6,
      shadows: 4,
      grainIntensity: 22,
      grainSize: 2,
      grainColorVariance: 18,
      vignetteIntensity: 18,
      vignetteRadius: 55,
      vignetteFeather: 60,
      fadeIntensity: 8,
      leakIntensity: 12,
      leakColor: 'warm',
      leakPosition: 'top-right',
      curveShadows: 4,
      curveHighlights: 4,
    },
  },
  {
    id: 'ektar',
    name: 'Kodak Ektar 100',
    descKey: 'desc_ektar',
    swatch: '#c2362c',
    state: {
      exposure: 2,
      temperature: 4,
      tint: -4,
      saturation: 18,
      contrast: 12,
      highlights: -8,
      shadows: -2,
      grainIntensity: 8,
      grainSize: 1,
      grainColorVariance: 6,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 75,
      curveHighlights: 6,
    },
  },
  {
    id: 'trix',
    name: 'Kodak Tri-X 400',
    descKey: 'desc_trix',
    swatch: '#2b2b2b',
    state: {
      saturation: -100,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      grainIntensity: 55,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 30,
      vignetteRadius: 55,
      vignetteFeather: 55,
      fadeIntensity: 6,
      curveShadows: 8,
      curveHighlights: 8,
    },
  },
  {
    id: 'superia',
    name: 'Fuji Superia 400',
    descKey: 'desc_superia',
    swatch: '#5fa05f',
    state: {
      exposure: 2,
      temperature: -4,
      tint: 6,
      saturation: 8,
      contrast: 4,
      highlights: -6,
      shadows: 4,
      grainIntensity: 20,
      grainSize: 2,
      grainColorVariance: 16,
      vignetteIntensity: 12,
      vignetteRadius: 60,
      vignetteFeather: 65,
      fadeIntensity: 6,
      curveShadows: 4,
      curveMidtones: 4,
    },
  },
  {
    id: 'c200',
    name: 'Fuji C200',
    descKey: 'desc_c200',
    swatch: '#6b8aa8',
    state: {
      exposure: 0,
      temperature: -6,
      tint: 2,
      saturation: -4,
      contrast: -6,
      highlights: 4,
      shadows: 6,
      grainIntensity: 16,
      grainSize: 2,
      grainColorVariance: 10,
      vignetteIntensity: 8,
      vignetteRadius: 65,
      vignetteFeather: 70,
      fadeIntensity: 12,
    },
  },
  {
    id: 'velvia',
    name: 'Fuji Velvia 50',
    descKey: 'desc_velvia',
    swatch: '#1e6fb0',
    state: {
      exposure: 2,
      temperature: -2,
      tint: -2,
      saturation: 30,
      contrast: 16,
      highlights: -10,
      shadows: -4,
      grainIntensity: 6,
      grainSize: 1,
      grainColorVariance: 4,
      vignetteIntensity: 10,
      vignetteRadius: 60,
      vignetteFeather: 70,
      curveShadows: -4,
      curveHighlights: 8,
    },
  },
  {
    id: 'eterna',
    name: 'Fuji Eterna 500',
    descKey: 'desc_eterna',
    swatch: '#7a8a92',
    state: {
      exposure: -2,
      temperature: -4,
      tint: 4,
      saturation: -14,
      contrast: -8,
      highlights: -8,
      shadows: 10,
      grainIntensity: 24,
      grainSize: 2,
      grainColorVariance: 14,
      vignetteIntensity: 14,
      vignetteRadius: 60,
      vignetteFeather: 70,
      fadeIntensity: 16,
      curveShadows: 8,
      curveHighlights: -6,
    },
  },
  {
    id: 'hp5',
    name: 'Ilford HP5 Plus',
    descKey: 'desc_hp5',
    swatch: '#3a3a3a',
    state: {
      saturation: -100,
      contrast: 14,
      highlights: -6,
      shadows: 8,
      grainIntensity: 45,
      grainSize: 3,
      grainColorVariance: 0,
      vignetteIntensity: 24,
      vignetteRadius: 58,
      vignetteFeather: 60,
      fadeIntensity: 10,
      curveShadows: 6,
      curveMidtones: -4,
    },
  },